#include "score_render_core.h"

#include <algorithm>
#include <chrono>
#include <cmath>
#include <cctype>
#include <limits>
#include <map>
#include <memory>
#include <mutex>
#include <optional>
#include <sstream>
#include <string>
#include <type_traits>
#include <unordered_map>
#include <unordered_set>
#include <vector>

#include <fluidsynth.h>

#include <QBuffer>
#include <QByteArray>
#include <QCoreApplication>
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QGuiApplication>
#include <QImage>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonParseError>
#include <QMetaObject>
#include <QMimeData>
#include <QPageLayout>
#include <QPageSize>
#include <QPdfWriter>
#include <QSaveFile>
#include <QThread>

#include "draw/drawmodule.h"
#include "draw/painter.h"
#include "engraving/compat/mscxcompat.h"
#include "engraving/compat/scoreaccess.h"
#include "engraving/editing/editsystemlocks.h"
#include "engraving/dom/accidental.h"
#include "engraving/dom/chord.h"
#include "engraving/dom/chordlist.h"
#include "engraving/dom/articulation.h"
#include "engraving/dom/dynamic.h"
#include "engraving/dom/excerpt.h"
#include "engraving/dom/factory.h"
#include "engraving/dom/hairpin.h"
#include "engraving/dom/harmony.h"
#include "engraving/dom/imageStore.h"
#include "engraving/dom/input.h"
#include "engraving/dom/instrtemplate.h"
#include "engraving/dom/jump.h"
#include "engraving/dom/layoutbreak.h"
#include "engraving/dom/lyrics.h"
#include "engraving/dom/marker.h"
#include "engraving/dom/measure.h"
#include "engraving/dom/measurerepeat.h"
#include "engraving/dom/masterscore.h"
#include "engraving/dom/navigate.h"
#include "engraving/dom/note.h"
#include "engraving/dom/ottava.h"
#include "engraving/dom/ledgerline.h"
#include "engraving/dom/page.h"
#include "engraving/dom/part.h"
#include "engraving/dom/pedal.h"
#include "engraving/dom/pitchspelling.h"
#include "engraving/dom/repeatlist.h"
#include "engraving/dom/rest.h"
#include "engraving/dom/segment.h"
#include "engraving/dom/shadownote.h"
#include "engraving/dom/slur.h"
#include "engraving/dom/spanner.h"
#include "engraving/dom/staff.h"
#include "engraving/dom/stem.h"
#include "engraving/dom/hook.h"
#include "engraving/dom/beam.h"
#include "engraving/dom/system.h"
#include "engraving/dom/systemlock.h"
#include "engraving/dom/tempotext.h"
#include "engraving/dom/textbase.h"
#include "engraving/dom/tie.h"
#include "engraving/dom/timesig.h"
#include "engraving/dom/tuplet.h"
#include "engraving/dom/utils.h"
#include "engraving/dom/volta.h"
#include "engraving/engravingmodule.h"
#include "engraving/editing/editdata.h"
#include "engraving/editing/editchord.h"
#include "engraving/editing/editnote.h"
#include "engraving/editing/editpart.h"
#include "engraving/editing/editspanner.h"
#include "engraving/editing/transpose.h"
#include "engraving/editing/undo.h"
#include "engraving/infrastructure/localfileinfoprovider.h"
#include "engraving/infrastructure/imimedata.h"
#include "engraving/infrastructure/mscio.h"
#include "engraving/infrastructure/mscreader.h"
#include "engraving/infrastructure/mscwriter.h"
#include "engraving/playback/playbackmodel.h"
#include "engraving/rendering/iscorerenderer.h"
#include "engraving/rendering/score/paint.h"
#include "engraving/rw/mscsaver.h"
#include "engraving/rw/inoutdata.h"
#include "engraving/rw/rwregister.h"
#include "audio/engine/internal/synthesizers/fluidsynth/soundmapping.h"
#include "global/globalmodule.h"
#include "global/iapplication.h"
#include "global/types/translatablestring.h"
#include "global/tests/mocks/applicationstub.h"
#include "io/buffer.h"
#include "log.h"
#include "importexport/musicxml/internal/import/importmusicxml.h"
#include "importexport/midi/internal/midiexport/exportmidi.h"
#include "importexport/musicxml/internal/export/exportmusicxml.h"
#include "importexport/musicxml/imusicxmlconfiguration.h"
#include "global/containers.h"
#include "mpe/events.h"
#include "mpe/mpetypes.h"
#include "mpe/iarticulationprofilesrepository.h"
#include "mpe/internal/articulationstringutils.h"
#include "modularity/ioc.h"
#include "modularity/imodulesetup.h"

// Defined in the CMake-generated articulation_profiles_embedded.cpp.
namespace msr { namespace render {
const std::map<std::string, std::string>& embeddedArticulationProfiles();
}}

#include "score_render_runtime.cpp"
#include "score_render_open_save.cpp"
#include "score_render_corruption.cpp"
#include "score_render_edit_state.cpp"
#include "score_render_edit_commands.cpp"
#include "score_render_playback.cpp"
#include "score_render_export.cpp"
#include "score_render_pages.cpp"
#include "score_render_audio.cpp"
#include "score_render_private.cpp"
#include "score_render_core_facade.inc"
